apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
  name: hello-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hello-nodejs
  template:
    metadata:
      labels:
        name: hello-nodejs
    spec:
      containers:
      - name: hello-nodejs
        image: dibemo/hello-nodejs:latest
        ports:
        - containerPort: 80
          name: http
