# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm install
  
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: dibemo/hello-nodejs
        tags: latest
        registry: docker.io
        dockerfile: ./dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}


  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: 'actions/checkout@v4'

    - uses: 'google-github-actions/auth@v2'
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}
 
    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: Get GKE credentials
      run: |
        gcloud components install gke-gcloud-auth-plugin
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} --zone ${{ secrets.GKE_ZONE }} --project ${{ secrets.GCP_PROJECT }}

    - name: Deploy to GKE
      run: |
        kubectl set image deployment/hello-nodejs hello-nodejs=dibemo/hello-nodejs:latest
        kubectl rollout status deployment/hello-nodejs
